chore: ACI-3810 add ACI_ReferenceApps_RBE_Bitrise_Accelerate_Production_Linux

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -233,6 +233,63 @@ workflows:
                 --extra_execution_platforms=//:linux_amd64
         title: Build Envoy with Bazel
     - deploy-to-bitrise-io@2: { }
+  ACI_ReferenceApps_RBE_Bitrise_Accelerate_Production_Linux:
+    steps:
+    - activate-ssh-key@4:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone@8: { }
+    - bundle::setup_bazel: { }
+    - script@1:
+        inputs:
+        - content: |
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+            
+            mkdir -p /opt/clang-14
+            wget -nv https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang+llvm-14.0.6-x86_64-linux-gnu-rhel-8.4.tar.xz
+            tar -xf clang+llvm-14.0.6-x86_64-linux-gnu-rhel-8.4.tar.xz -C /opt/clang-14 --strip-components=1
+            
+            # remove asdf bindings from the $PATH
+            export PATH=$(echo "$PATH" | tr ':' '\n' | grep -v '/root/.asdf' | paste -sd:)
+            echo "PATH=$PATH"
+            
+            bazel/setup_clang.sh /opt/clang-14
+        title: Install clang
+    - script@1:
+        inputs:
+        - content: |
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+            
+            echo "common --show_timestamps" >> .bazelrc
+            echo "common --announce_rc" >> .bazelrc
+            echo "common --color=yes" >> .bazelrc
+            echo "common --config=remote_bitrise" >> .bazelrc
+            echo "common --config=linux" >> .bazelrc
+            echo "build --config=clang" >> .bazelrc
+            
+            BUILD_RANDOM=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16)
+            #BUILD_RANDOM=cph3CbbaNXnc6bTS
+            
+            OVERRIDE_ENDPOINTS="--remote_executor=grpcs://bitrise-accelerate.services.bitrise.io:443 --remote_cache=grpcs://bitrise-accelerate.services.bitrise.io:443"
+            
+            bazel build -j 1000 -c opt //:envoy $OVERRIDE_ENDPOINTS \
+                --repo_env=BUILD_RANDOM=${BUILD_RANDOM} \
+                --action_env=BUILD_RANDOM=${BUILD_RANDOM} \
+                --define=BUILD_RANDOM=${BUILD_RANDOM} \
+                --extra_execution_platforms=//:linux_amd64
+        title: Build Envoy with Bazel
+    - deploy-to-bitrise-io@2: { }
   ACI_ReferenceApps_RBE_Staging_IAD_Linux:
     steps:
     - activate-ssh-key@4:
